### PR TITLE
adding new placeholder image

### PR DESCRIPTION
**Pull request by crownedpigeon**
@macjabeth went with a 'coming soon' movie poster feel and peeking bunny face--totally open to iterations or providing some more choices, just let me know!

### CODE REVIEW

**Comment by macjabeth** [comment]
@crownedpigeon Awe, the peeking bunny is adorbs. 😍

It's an excellent start, but I think the text needs to be changed to something more encompassing since there are movies and tv shows that probably won't be adding posters anytime soon. 💁 

I know it's a bit hidden and not _as_ important, but I noticed there's no placeholder image for the dialog when it opens... and I was hoping something could be added for that too if you're up to it.

**Comment by crownedpigeon** [comment]
sure thing 😊! as for the text, maybe something like "image unavailable"? another option is doing away with the text portion altogether and putting a '?' above the bunny's head, or something similar

**Comment by macjabeth** [comment]
@crownedpigeon I'm thinking either including the film title or even just the word "Showbunny" between the film strip.

**Comment by macjabeth** [comment]
Looks good! Thanks, @crownedpigeon!

**Pull request merged**
