### PR TITLE
Fixes #43

### LINKED ISSUE #43: List items should be direct descendents of unordered lists
Right now we have the `<media-poster>` tags as direct descendants of the `<ul>` tags.

This is structured incorrectly. The `<media-poster>` tags should be descendants of `<li>` tags.

### PR DESCRIPTION
**Pull request by Bassadin**

### CODE REVIEW

**Comment by Bassadin** [comment]
This is like my second PR ever, feel free to scold me if I did something wrong :)

**Comment by macjabeth** [comment]
Hey @Bassadin! Thanks for the PR. 🙂

I'll take a look at this during my live stream tomorrow.

**Comment by macjabeth** [comment]
@Bassadin Hey. I tried to merge the conflicts and push up to your branch, but I'm unauthorised unfortunately.

So I'm going to just merge these changes in directly and push them up to the rebirth branch. Thank you for doing this PR!

**Comment by Bassadin** [comment]
Oh. Any chance what I can do to avoid that next time? I think I I used gitkraken to create the branch, I thought the original owner of the repo always has some kind of access to each fork.

**Comment by macjabeth** [comment]
> Oh. Any chance what I can do to avoid that next time? I think I I used gitkraken to create the branch, I thought the original owner of the repo always has some kind of access to each fork.

Hey @Bassadin - check out this link for the future. 🙂

"Allowing changes to a pull request branch created from a fork - GitHub Docs" https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Bassadin** [comment]
Thanks for the link :) Did you talk about the issue during your stream? I skipped through it a bit but couldn't find it :o

**Comment by macjabeth** [comment]
> Thanks for the link :) Did you talk about the issue during your stream? I skipped through it a bit but couldn't find it :o

I'm afraid not. I was planning to but decided to switch gears after reviewing the first PR. Perhaps next time though!

**Pull request merged**
